---
title: "lb2"
output: html_document
date: "2024-03-14"
---

```
knitr::opts_chunk$set(echo = TRUE)
```
libraries
```{r}
library(rvest)
library(dplyr)
library(polite)
library(stringr)
```

```{r}
url <- "https://www.amazon.com/YMC-Beginner-Thickness-Pickguards-Electronic/product-reviews/B01I8L5HT6/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"

session1 <- bow(url, user_agent = "educational purposes")
session1
url1 <- read_html(url)
```
1st product
```{r}
#get the product name
productname <- url1 %>%
  html_nodes("h1.a-size-large.a-text-ellipsis") %>%
  html_text()

#get the reviewer's name
reviewername <- url1 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername1 <- reviewername[4:14]#subset reviewer to get only 10 reviewers. 
removedup1 <- subsetreviewername1[-3]
#get the star ratings of the reviewer
starreview <- url1 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#extract only the star ratings
starsplit <- str_extract(starreview, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit

#get the title review and remove the star rate.
review_titles <- lapply(starreview, function(title) {
  title <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", title)
  title <- trimws(title)
  return(title)
})
review_titles
#get the date of the review
dateofreview <- url1 %>%
  html_nodes("span.review-date") %>%
  html_text()

#extract only the month, day, and year
splitdatereview <- str_extract(dateofreview, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate <- splitdatereview[3:12]

#get the text content of the review
textreview <- url1 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#function for removing emojis in the text
remove_emojis <- function(textreview) {
  str_remove_all(textreview, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview <- remove_emojis(textreview)

#remove the white spaces
cleantext <- trimws(textreview)
cleantext
```
1st product/2
```{r}
urlprod1_2 <- "https://www.amazon.com/YMC-Beginner-Thickness-Pickguards-Electronic/product-reviews/B01I8L5HT6/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

session2 <- bow(url2nd, user_agent = "educational purposes")

url1_2 <- read_html(urlprod1_2)
```
1.2 product
```{r}
#get the reviewer's name
reviewername1_2 <- url1_2 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()


subsetreviewername1_2 <- reviewername1_2[3:13] #subset the 2nd page reviewer to get only the 10 reviewers.
removedup <- subsetreviewername1_2[-10] #remove the duplicate of the 9th user.
removedup
#get the star ratings of the reviewer
starreview1_2 <- url1_2 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit1_2 <- str_extract(starreview1_2, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit1_2

#get the review title and use gsub to remove the star ratings
review_titles1_2 <- lapply(starreview1_2, function(revtitle1_2) {
  revtitle1_2 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle1_2)
  revtitle1_2 <- trimws(revtitle1_2)
  return(revtitle1_2)
})
review_titles1_2

#get the date of the review
dateofreview1_2 <- url1_2 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview1_2 <- str_extract(dateofreview1_2, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate1_2 <- splitdatereview1_2[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview1_2 <- url1_2 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis1_2 <- function(textreview1_2) {
  str_remove_all(textreview1_2, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview1_2 <- remove_emojis1_2(textreview1_2)

#get the clean text without white spaces
cleantext1_2 <- trimws(textreview1_2)

cleantext1_2[6:7] = NA #replace 6 and 7 with NA because it's from a different language.
cleantext1_2
```

```
url3 <- "https://www.amazon.com/YMC-Beginner-Thickness-Pickguards-Electronic/product-reviews/B01I8L5HT6/ref=cm_cr_arp_d_paging_btm_3?ie=UTF8&pageNumber=3&reviewerType=all_reviews"

session3 <- bow(url3, user_agent = "educational purposes")

url1_3 <- read_html(url3)
``` 

```{r}
#get the reviewer's name
reviewername1_3 <- url1_3 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername1_3 <- reviewername1_3[3:13] #subset the 2nd page reviewer to get only the 10 reviewers.
removedup3 <- subsetreviewername1_3[-4]
#get the star ratings of the reviewer
starreview1_3 <- url1_3 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit1_3 <- str_extract(starreview1_3, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit1_3

#get the review title and use gsub to remove the star ratings
review_titles1_3 <- lapply(starreview1_3, function(revtitle1_3) {
  revtitle1_3 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle1_3)
  revtitle1_3 <- trimws(revtitle1_3)
  return(revtitle1_3)
})
review_titles1_3

#get the date of the review
dateofreview1_3 <- url1_3 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview1_3 <- str_extract(dateofreview1_3, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate1_3 <- splitdatereview1_3[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview1_3 <- url1_3 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis1_3 <- function(textreview1_3) {
  str_remove_all(textreview1_3, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview1_3 <- remove_emojis1_3(textreview1_3)

#get the clean text without white spaces
cleantext1_3 <- trimws(textreview1_3)
cleantext1_3
```
```
url4 <- "https://www.amazon.com/YMC-Beginner-Thickness-Pickguards-Electronic/product-reviews/B01I8L5HT6/ref=cm_cr_arp_d_paging_btm_4?ie=UTF8&pageNumber=4&reviewerType=all_reviews"

session4 <- bow(url4, user_agent = "educational purposes")

url1_4 <- read_html(url4) 
```

```{r}
#get the reviewer's name
reviewername1_4 <- url1_4 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername1_4 <- reviewername1_4[3:12] #subset the 4th page reviewer to get only the 10 reviewers.

#get the star ratings of the reviewer
starreview1_4 <- url1_4 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit1_4 <- str_extract(starreview1_4, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit1_4

#get the review title and use gsub to remove the star ratings
review_titles1_4 <- lapply(starreview1_4, function(revtitle1_4) {
  revtitle1_4 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle1_4)
  revtitle1_4 <- trimws(revtitle1_4)
  return(revtitle1_4)
})
review_titles1_4

#get the date of the review
dateofreview1_4 <- url1_4 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview1_4 <- str_extract(dateofreview1_4, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate1_4 <- splitdatereview1_4[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview1_4 <- url1_4 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis1_4 <- function(textreview1_4) {
  str_remove_all(textreview1_4, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview1_4 <- remove_emojis1_4(textreview1_4)

#get the clean text without white spaces
cleantext1_4 <- trimws(textreview1_4)
cleantext1_4
```
```
url5 <- "https://www.amazon.com/YMC-Beginner-Thickness-Pickguards-Electronic/product-reviews/B01I8L5HT6/ref=cm_cr_arp_d_paging_btm_5?ie=UTF8&pageNumber=5&reviewerType=all_reviews"
session5 <- bow(url5, user_agent = "educational purposes")
url1_5 <- read_html(url5)
```

```{r}
#get the reviewer's name
reviewername1_5 <- url1_5 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername1_5 <- reviewername1_5[3:13] #subset the 5th page reviewer to get only the 10 reviewers.
removedup5 <-subsetreviewername1_5[-2] #remove the duplicae
#get the star ratings of the reviewer
starreview1_5 <- url1_5 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit1_5 <- str_extract(starreview1_5, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit1_5

#get the review title and use gsub to remove the star ratings
review_titles1_5 <- lapply(starreview1_5, function(revtitle1_5) {
  revtitle1_5 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle1_5)
  revtitle1_5 <- trimws(revtitle1_5)
  return(revtitle1_5)
})
review_titles1_5

#get the date of the review
dateofreview1_5 <- url1_5 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview1_5 <- str_extract(dateofreview1_5, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate1_5 <- splitdatereview1_5[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview1_5 <- url1_5 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis1_5 <- function(textreview1_5) {
  str_remove_all(textreview1_5, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview1_5 <- remove_emojis1_5(textreview1_5)

#get the clean text without white spaces
cleantext1_5 <- trimws(textreview1_5)
cleantext1_5
```
```{r}
#combine the items first
combinedreviewers <- c(removedup1,removedup,removedup3,subsetreviewername1_4,removedup5)

combinedstars <- c(starsplit,starsplit1_2, starsplit1_3, starsplit1_4, starsplit1_5)

combineddate <- c(subsetdate, subsetdate1_2, subsetdate1_3, subsetdate1_4, subsetdate1_5)

combinedtext <- c(cleantext, cleantext1_2, cleantext1_3, cleantext1_4, cleantext1_5)

product1df <- data.frame( ProductName = productname,
                          reviewers = combinedreviewers,
                          star_rates = combinedstars,
                         date_of_review = combineddate,
                         text_review = combinedtext)
product1df
write.csv(product1df, "FirstProduct.csv")
```

```
url2 <-"https://www.amazon.com/Blink-Video-Doorbell/product-reviews/B08SG2MS3V/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
session2_1 <- bow(url2, user_agent = "educational purposes")

url2_1 <- read_html(url2)
```

```{r}
#get the product name
productname2 <- url2_1 %>%
  html_nodes("h1.a-size-large.a-text-ellipsis") %>%
  html_text()
productname2
#get the reviewer's name
reviewername2_1 <- url2_1 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername2_1 <- reviewername2_1[3:13] #subset the 5th page reviewer to get only the 10 reviewers.
removedup2_1 <-subsetreviewername2_1[-7] #remove the duplicate
#get the star ratings of the reviewer
starreview2_1 <- url2_1 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit2_1 <- str_extract(starreview2_1, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit2_1

#get the review title and use gsub to remove the star ratings
review_titles2_1 <- lapply(starreview2_1, function(revtitle2_1) {
  revtitle2_1<- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle2_1)
  revtitle2_1 <- trimws(revtitle2_1)
  return(revtitle2_1)
})
review_titles2_1

#get the date of the review
dateofreview2_1 <- url2_1 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview2_1 <- str_extract(dateofreview2_1, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate2_1 <- splitdatereview2_1[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview2_1 <- url2_1 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis2_1 <- function(textreview2_1) {
  str_remove_all(textreview2_1, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview2_1 <- remove_emojis2_1(textreview2_1)

#get the clean text without white spaces
cleantext2_1 <- trimws(textreview2_1)
cleantext2_1
```
```
urlprod2_2 <- "https://www.amazon.com/Blink-Video-Doorbell/product-reviews/B08SG2MS3V/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
session2_2 <- bow(urlprod2_2, user_agent = "educational purposes")
url2_2 <- read_html(urlprod2_2)
```

```{r}
#get the reviewer's name
reviewername2_2 <- url2_2 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername2_2 <- reviewername2_2[3:12] #subset the 5th page reviewer to get only the 10 reviewers.

#get the star ratings of the reviewer
starreview2_2 <- url2_2 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit2_2 <- str_extract(starreview2_2, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit2_2

#get the review title and use gsub to remove the star ratings
review_titles2_2 <- lapply(starreview2_2, function(revtitle2_2) {
  revtitle2_2 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle2_2)
  revtitle2_2 <- trimws(revtitle2_2)
  return(revtitle2_2)
})
review_titles2_2

#get the date of the review
dateofreview2_2 <- url2_2 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview2_2 <- str_extract(dateofreview2_2, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate2_2 <- splitdatereview2_2[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview2_2 <- url2_2 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis2_2 <- function(textreview2_2) {
  str_remove_all(textreview2_2, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview2_2 <- remove_emojis2_2(textreview2_2)

#get the clean text without white spaces
cleantext2_2 <- trimws(textreview2_2)
cleantext2_2
```
```
urlprod2_3 <- "https://www.amazon.com/Blink-Video-Doorbell/product-reviews/B08SG2MS3V/ref=cm_cr_arp_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
session2_3 <- bow(urlprod2_3, user_agent = "educational purposes")
url2_3 <- read_html(urlprod2_3)
```

```{r}
#get the reviewer's name
reviewername2_3 <- url2_3 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername2_3 <- reviewername2_3[3:14] #subset the 5th page reviewer to get only the 10 reviewers.
removedup2_3 <- subsetreviewername2_3[-c(5, 9)]#remove the duplicate
removedup2_3
#get the star ratings of the reviewer
starreview2_3 <- url2_3 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit2_3 <- str_extract(starreview2_3, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit2_3

#get the review title and use gsub to remove the star ratings
review_titles2_3 <- lapply(starreview2_3, function(revtitle2_3) {
  revtitle2_3 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle2_3)
  revtitle2_3 <- trimws(revtitle2_3)
  return(revtitle2_3)
})
review_titles2_3

#get the date of the review
dateofreview2_3 <- url2_3 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview2_3 <- str_extract(dateofreview2_3, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate2_3 <- splitdatereview2_3[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview2_3 <- url2_3 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis2_3 <- function(textreview2_3) {
  str_remove_all(textreview2_3, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview2_3 <- remove_emojis2_3(textreview2_3)

#get the clean text without white spaces
cleantext2_3 <- trimws(textreview2_3)
cleantext2_3
```

```
urlprod2_4 <- "https://www.amazon.com/Blink-Video-Doorbell/product-reviews/B08SG2MS3V/ref=cm_cr_getr_d_paging_btm_next_4?ie=UTF8&reviewerType=all_reviews&pageNumber=4"
session2_4 <- bow(urlprod2_4, user_agent = "educational purposes")
url2_4 <- read_html(urlprod2_4)
```

```{r}
#get the reviewer's name
reviewername2_4 <- url2_4 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername2_4 <- reviewername2_4[3:13] #subset the 5th page reviewer to get only the 10 reviewers.
removedup2_4 <- subsetreviewername2_4[-9] #remove the duplicae
#get the star ratings of the reviewer
starreview2_4 <- url2_4 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit2_4 <- str_extract(starreview2_4, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit2_4

#get the review title and use gsub to remove the star ratings
review_titles2_4 <- lapply(starreview2_4, function(revtitle2_4) {
  revtitle2_4 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle2_4)
  revtitle2_4 <- trimws(revtitle2_4)
  return(revtitle2_4)
})
review_titles2_4

#get the date of the review
dateofreview2_4 <- url2_4 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview2_4 <- str_extract(dateofreview2_4, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate2_4 <- splitdatereview2_4[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview2_4 <- url2_4 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis2_4 <- function(textreview2_4) {
  str_remove_all(textreview2_4, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview2_4 <- remove_emojis2_4(textreview2_4)

#get the clean text without white spaces
cleantext2_4 <- trimws(textreview2_4)
cleantext2_4
```
```
urlprod2_5 <- "https://www.amazon.com/Blink-Video-Doorbell/product-reviews/B08SG2MS3V/ref=cm_cr_getr_d_paging_btm_next_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5"
session2_5 <- bow(urlprod2_5, user_agent = "educational purposes")
url2_5 <- read_html(urlprod2_5)
```

```{r}
#get the reviewer's name
reviewername2_5 <- url2_5 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername2_5 <- reviewername2_5[3:14] #subset the 5th page reviewer to get only the 10 reviewers.
removedup2_5 <- subsetreviewername2_5[-c(11, 2)] #remove the duplicae
#get the star ratings of the reviewer
starreview2_5 <- url2_5 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit2_5 <- str_extract(starreview2_5, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit2_5

#get the review title and use gsub to remove the star ratings
review_titles2_5 <- lapply(starreview2_5, function(revtitle2_5) {
  revtitle2_5 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle2_5)
  revtitle2_5 <- trimws(revtitle2_5)
  return(revtitle2_5)
})
review_titles2_5

#get the date of the review
dateofreview2_5 <- url2_5 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview2_5 <- str_extract(dateofreview2_5, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate2_5 <- splitdatereview2_5[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview2_5 <- url2_5 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis2_5 <- function(textreview2_5) {
  str_remove_all(textreview2_5, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview2_5 <- remove_emojis2_5(textreview2_5)

#get the clean text without white spaces
cleantext2_5 <- trimws(textreview2_5)
cleantext2_5

```

```{r}
#combine the items first
combinedreviewers2 <- c(removedup2_1,subsetreviewername2_2,removedup2_3,removedup2_4,removedup2_5)

combinedstars2 <- c(starsplit2_1,starsplit2_2, starsplit2_3, starsplit2_4, starsplit2_5)

combineddate2 <- c(subsetdate2_1, subsetdate2_2, subsetdate2_3, subsetdate2_4, subsetdate2_5)

combinedtext2 <- c(cleantext2_1, cleantext2_2, cleantext2_3, cleantext2_4, cleantext2_5)

product2df <- data.frame( ProductName = productname2,
                          reviewers = combinedreviewers2,
                          star_rates = combinedstars2,
                         date_of_review = combineddate2,
                         text_review = combinedtext2)
product2df
write.csv(product2df, "SecondProduct.csv")
```
```
urlprod3 <- "https://www.amazon.com/Flgocexs-Wireless-Carplay-Adapter-Original/product-reviews/B0C4GWHN73/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
session3 <- bow(urlprod3, user_agent = "educational purposes")
url3_1 <- read_html(urlprod3)
```
```{r}
#get the product name
productname3 <- url3_1 %>%
  html_nodes("h1.a-size-large.a-text-ellipsis") %>%
  html_text()

#get the reviewer's name
reviewername3_1 <- url3_1 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername3_1 <- reviewername3_1[3:13] #subset the 5th page reviewer to get only the 10 reviewers.
removedup3_1 <- subsetreviewername3_1[(-2)] #remove the duplicate
#get the star ratings of the reviewer
starreview3_1 <- url3_1 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit3_1 <- str_extract(starreview3_1, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit3_1

#get the review title and use gsub to remove the star ratings
review_titles3_1 <- lapply(starreview3_1, function(revtitle3_1) {
  revtitle3_1 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle3_1)
  revtitle3_1 <- trimws(revtitle3_1)
  return(revtitle3_1)
})
review_titles3_1

#get the date of the review
dateofreview3_1 <- url3_1 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview3_1 <- str_extract(dateofreview3_1, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate3_1 <- splitdatereview3_1[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview3_1 <- url3_1 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis3_1 <- function(textreview3_1) {
  str_remove_all(textreview3_1, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview3_1 <- remove_emojis3_1(textreview3_1)

#get the clean text without white spaces
cleantext3_1 <- trimws(textreview3_1)
cleantext3_1
```
```
urlprod3_2 <- "https://www.amazon.com/Flgocexs-Wireless-Carplay-Adapter-Original/product-reviews/B0C4GWHN73/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
session3_2 <- bow(urlprod3_2, user_agent = "educational purposes")
url3_2 <- read_html(urlprod3_2)
```

```{r}
#get the reviewer's name
reviewername3_2 <- url3_2 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername3_2 <- reviewername3_2[3:12] #subset the 5th page reviewer to get only the 10 reviewers.
subsetreviewername3_2[4] = NA
subsetreviewername3_2
#get the star ratings of the reviewer
starreview3_2 <- url3_2 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit3_2 <- str_extract(starreview3_2, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit3_2

#get the review title and use gsub to remove the star ratings
review_titles3_2 <- lapply(starreview3_2, function(revtitle3_2) {
  revtitle3_2 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle3_2)
  revtitle3_2 <- trimws(revtitle3_2)
  return(revtitle3_2)
})
review_titles3_2
review_titles3_2[c(4,10,7)] = NA
#get the date of the review
dateofreview3_2 <- url3_2 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview3_2 <- str_extract(dateofreview3_2, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate3_2 <- splitdatereview3_2[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview3_2 <- url3_2 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis3_2 <- function(textreview3_2) {
  str_remove_all(textreview3_2, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview3_2 <- remove_emojis3_2(textreview3_2)

#get the clean text without white spaces
cleantext3_2 <- trimws(textreview3_2)
cleantext3_2[c(4,7,10)] = NA
cleantext3_2
```
```
urlprod3_3 <- "https://www.amazon.com/Flgocexs-Wireless-Carplay-Adapter-Original/product-reviews/B0C4GWHN73/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
session3_3 <- bow(urlprod3_3, user_agent = "educational purposes")
url3_3 <- read_html(urlprod3_3)
```

```{r}
#get the reviewer's name
reviewername3_3 <- url3_3 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername3_3 <- reviewername3_3[3:13] #subset the 5th page reviewer to get only the 10 reviewers.
removedup3_3 <- subsetreviewername3_3[(-4)] #remove the duplicate
#get the star ratings of the reviewer
starreview3_3 <- url3_3 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit3_3 <- str_extract(starreview3_3, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit3_3

#get the review title and use gsub to remove the star ratings
review_titles3_3 <- lapply(starreview3_3, function(revtitle3_3) {
  revtitle3_3 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle3_3)
  revtitle3_3 <- trimws(revtitle3_3)
  return(revtitle3_3)
})
review_titles3_1

#get the date of the review
dateofreview3_3 <- url3_3 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview3_3 <- str_extract(dateofreview3_3, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate3_3 <- splitdatereview3_3[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.

#get the content of the review
textreview3_3 <- url3_3 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis3_3 <- function(textreview3_3) {
  str_remove_all(textreview3_3, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview3_3 <- remove_emojis3_3(textreview3_3)

#get the clean text without white spaces
cleantext3_3 <- trimws(textreview3_3)
cleantext3_3
cleantext3_3[c(10,3)] = NA
removeUnnecessary3_3 <- gsub("The media could not be loaded.\n                \n            \n                \n            \n            \n        \n    \n    \n", "" ,cleantext3_3)
removeUnnecessary3_3
```
```
urlprod3_4 <- "https://www.amazon.com/Flgocexs-Wireless-Carplay-Adapter-Original/product-reviews/B0C4GWHN73/ref=cm_cr_getr_d_paging_btm_next_4?ie=UTF8&reviewerType=all_reviews&pageNumber=4"
session3_4 <- bow(urlprod3_4, user_agent = "educational purposes")
url3_4 <- read_html(urlprod3_4)
```

```{r}
#get the reviewer's name
reviewername3_4 <- url3_4 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername3_4 <- reviewername3_4[3:14] #subset the 5th page reviewer to get only the 10 reviewers.
removedup3_4 <- subsetreviewername3_4[-c(5,7)] #remove the duplicate
#get the star ratings of the reviewer
starreview3_4 <- url3_4 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit3_4 <- str_extract(starreview3_4, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit3_4

#get the review title and use gsub to remove the star ratings
review_titles3_4 <- lapply(starreview3_4, function(revtitle3_4) {
  revtitle3_4 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle3_4)
  revtitle3_4 <- trimws(revtitle3_4)
  return(revtitle3_4)
})
review_titles3_4
review_titles3_4[5] = NA

#get the date of the review
dateofreview3_4 <- url3_4 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview3_4 <- str_extract(dateofreview3_4, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate3_4 <- splitdatereview3_4[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate3_4
#get the content of the review
textreview3_4 <- url3_4 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis3_4 <- function(textreview3_4) {
  str_remove_all(textreview3_4, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview3_4 <- remove_emojis3_4(textreview3_4)

#get the clean text without white spaces
cleantext3_4 <- trimws(textreview3_4)
cleantext3_4[5] = NA
cleantext3_4
```
```
urlprod3_5 <- "https://www.amazon.com/Flgocexs-Wireless-Carplay-Adapter-Original/product-reviews/B0C4GWHN73/ref=cm_cr_getr_d_paging_btm_next_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5"
session3_5 <- bow(urlprod3_5, user_agent = "educational purposes")
url3_5 <- read_html(urlprod3_5)
```

```{r}
#get the reviewer's name
reviewername3_5 <- url3_5 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername3_5 <- reviewername3_5[3:15] #subset the 5th page reviewer to get only the 10 reviewers.
removedup3_5 <- subsetreviewername3_5[-c(10,7,11)] #remove the duplicate
#get the star ratings of the reviewer
starreview3_5 <- url3_5 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit3_5 <- str_extract(starreview3_5, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit3_5

#get the review title and use gsub to remove the star ratings
review_titles3_5 <- lapply(starreview3_5, function(revtitle3_5) {
  revtitle3_5 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle3_5)
  revtitle3_5 <- trimws(revtitle3_5)
  return(revtitle3_5)
})

review_titles3_5[6] = NA
review_titles3_5
#get the date of the review
dateofreview3_5 <- url3_5 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview3_5 <- str_extract(dateofreview3_5, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate3_5 <- splitdatereview3_5[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate3_5
#get the content of the review
textreview3_5 <- url3_5 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis3_5 <- function(textreview3_5) {
  str_remove_all(textreview3_5, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview3_5 <- remove_emojis3_5(textreview3_5)

#get the clean text without white spaces
cleantext3_5 <- trimws(textreview3_5)
cleantext3_5[6] = NA
cleantext3_5
```
```{r}
#combine the items first
combinedreviewers3 <- c(removedup3_1,subsetreviewername3_2,removedup3_3,removedup3_4,removedup3_5)

combinedstars3 <- c(starsplit3_1,starsplit3_2, starsplit3_3, starsplit3_4, starsplit3_5)

combineddate3 <- c(subsetdate3_1, subsetdate3_2, subsetdate3_3, subsetdate3_4, subsetdate3_5)

combinedtext3 <- c(cleantext3_1, cleantext3_2, cleantext3_3, cleantext3_4, cleantext3_5)

product3df <- data.frame( ProductName = productname3,
                          reviewers = combinedreviewers3,
                          star_rates = combinedstars3,
                         date_of_review = combineddate3,
                         text_review = combinedtext3)
product3df
write.csv(product3df, "ThirdProduct.csv")
```

```
urlprod4_1 <- "https://www.amazon.com/Wireless-Bluetooth-Headphones-Earphones-BMANI-VEAT00L/product-reviews/B09FLNSYDZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
session4_1 <- bow(urlprod4_1, user_agent = "educational purposes")
url4_1 <- read_html(urlprod4_1)
```

```{r}
productname4 <- url4_1 %>%
  html_nodes("h1.a-size-large.a-text-ellipsis") %>%
  html_text()
#get the reviewer's name
reviewername4_1 <- url4_1 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername4_1 <- reviewername4_1[3:14] #subset the 5th page reviewer to get only the 10 reviewers.
removedup4_1 <- subsetreviewername4_1[-c(5, 10)] #remove the duplicate
#get the star ratings of the reviewer
starreview4_1 <- url4_1 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit4_1 <- str_extract(starreview4_1, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit4_1

#get the review title and use gsub to remove the star ratings
review_titles4_1 <- lapply(starreview4_1, function(revtitle4_1) {
  revtitle4_1 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle4_1)
  revtitle4_1 <- trimws(revtitle4_1)
  return(revtitle4_1)
})
review_titles4_1


#get the date of the review
dateofreview4_1 <- url4_1 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview4_1 <- str_extract(dateofreview4_1, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate4_1 <- splitdatereview4_1[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate4_1
#get the content of the review
textreview4_1 <- url4_1 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis4_1 <- function(textreview4_1) {
  str_remove_all(textreview4_1, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview4_1 <- remove_emojis4_1(textreview4_1)

#get the clean text without white spaces
cleantext4_1 <- trimws(textreview4_1)
cleantext4_1
```
```
urlprod4_2 <- "https://www.amazon.com/Wireless-Bluetooth-Headphones-Earphones-BMANI-VEAT00L/product-reviews/B09FLNSYDZ/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
session4_2 <- bow(urlprod4_2, user_agent = "educational purposes")
url4_2 <- read_html(urlprod4_2)
```

```{r}
#get the reviewer's name
reviewername4_2 <- url4_2 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername4_2 <- reviewername4_2[3:14] #subset the 5th page reviewer to get only the 10 reviewers.
removedup4_2 <- subsetreviewername4_2[-c(10,1)] #remove the duplicate
#get the star ratings of the reviewer
starreview4_2 <- url4_2 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit4_2 <- str_extract(starreview4_2, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit4_2

#get the review title and use gsub to remove the star ratings
review_titles4_2 <- lapply(starreview4_2, function(revtitle4_2) {
  revtitle4_2 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle4_2)
  revtitle4_2 <- trimws(revtitle4_2)
  return(revtitle4_2)
})
review_titles4_2


#get the date of the review
dateofreview4_2 <- url4_2 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview4_2 <- str_extract(dateofreview4_2, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate4_2 <- splitdatereview4_2[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate4_2
#get the content of the review
textreview4_2 <- url4_2 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis4_2 <- function(textreview4_2) {
  str_remove_all(textreview4_2, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview4_2 <- remove_emojis4_2(textreview4_2)

#get the clean text without white spaces
cleantext4_2 <- trimws(textreview4_2)
cleantext4_2
```
```
urlprod4_3 <- "https://www.amazon.com/Wireless-Bluetooth-Headphones-Earphones-BMANI-VEAT00L/product-reviews/B09FLNSYDZ/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
session4_3 <- bow(urlprod4_3, user_agent = "educational purposes")
url4_3 <- read_html(urlprod4_3)
```

```{r}

#get the reviewer's name
reviewername4_3 <- url4_3 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername4_3 <- reviewername4_3[3:14] #subset the 5th page reviewer to get only the 10 reviewers.
removedup4_3 <- subsetreviewername4_3[-c(2, 8)] #remove the duplicate
#get the star ratings of the reviewer
starreview4_3 <- url4_3 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit4_3 <- str_extract(starreview4_3, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit4_3

#get the review title and use gsub to remove the star ratings
review_titles4_3 <- lapply(starreview4_3, function(revtitle4_3) {
  revtitle4_3 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle4_3)
  revtitle4_3 <- trimws(revtitle4_3)
  return(revtitle4_3)
})
review_titles4_3


#get the date of the review
dateofreview4_3 <- url4_3 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview4_3 <- str_extract(dateofreview4_3, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate4_3 <- splitdatereview4_3[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate4_3
#get the content of the review
textreview4_3 <- url4_3 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis4_3 <- function(textreview4_3) {
  str_remove_all(textreview4_3, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview4_3 <- remove_emojis4_3(textreview4_3)

#get the clean text without white spaces
cleantext4_3 <- trimws(textreview4_3)
cleantext4_3
```

```
urlprod4_4 <- "https://www.amazon.com/Wireless-Bluetooth-Headphones-Earphones-BMANI-VEAT00L/product-reviews/B09FLNSYDZ/ref=cm_cr_arp_d_paging_btm_4?ie=UTF8&pageNumber=4&reviewerType=all_reviews"
session4_4 <- bow(urlprod4_4, user_agent = "educational purposes")
url4_4 <- read_html(urlprod4_4)
```

```{r}
#get the reviewer's name
reviewername4_4 <- url4_4 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername4_4 <- reviewername4_4[3:12] #subset the 5th page reviewer to get only the 10 reviewers.

#get the star ratings of the reviewer
starreview4_4 <- url4_4 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit4_4 <- str_extract(starreview4_4, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit4_4

#get the review title and use gsub to remove the star ratings
review_titles4_4 <- lapply(starreview4_4, function(revtitle4_4) {
  revtitle4_4 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle4_4)
  revtitle4_4 <- trimws(revtitle4_4)
  return(revtitle4_4)
})
review_titles4_4


#get the date of the review
dateofreview4_4 <- url4_4 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview4_4 <- str_extract(dateofreview4_4, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate4_4 <- splitdatereview4_4[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate4_4
#get the content of the review
textreview4_4 <- url4_4 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis4_4 <- function(textreview4_4) {
  str_remove_all(textreview4_4, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview4_4 <- remove_emojis4_4(textreview4_4)

#get the clean text without white spaces
cleantext4_4 <- trimws(textreview4_4)
cleantext4_4
```

```
 urlprod4_5 <-"https://www.amazon.com/Wireless-Bluetooth-Headphones-Earphones-BMANI-VEAT00L/product-reviews/B09FLNSYDZ/ref=cm_cr_arp_d_paging_btm_next_5?ie=UTF8&pageNumber=5&reviewerType=all_reviews"
session4_5 <- bow(urlprod4_5, user_agent = "educational purposes")
url4_5 <- read_html(urlprod4_5)
```

```{r}
#get the reviewer's name
reviewername4_5 <- url4_5 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername4_5 <- reviewername4_5[3:13] #subset the 5th page reviewer to get only the 10 reviewers.
removedup4_5 <- subsetreviewername4_5[(-7)] #remove the duplicate
#get the star ratings of the reviewer
starreview4_5 <- url4_5 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit4_5 <- str_extract(starreview4_5, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit4_5

#get the review title and use gsub to remove the star ratings
review_titles4_5 <- lapply(starreview4_5, function(revtitle4_5) {
  revtitle4_5 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle4_5)
  revtitle4_5 <- trimws(revtitle4_5)
  return(revtitle4_5)
})
review_titles4_5


#get the date of the review
dateofreview4_5 <- url4_5 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview4_5 <- str_extract(dateofreview4_5, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate4_5 <- splitdatereview4_5[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate4_5
#get the content of the review
textreview4_5 <- url4_5 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis4_5 <- function(textreview4_5) {
  str_remove_all(textreview4_5, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview4_5 <- remove_emojis4_5(textreview4_5)

#get the clean text without white spaces
cleantext4_5 <- trimws(textreview4_5)
cleantext4_5
```
```{r}
#combine the items first

combinedreviewers4 <- c(removedup4_1,removedup4_2,removedup4_3,subsetreviewername4_4,removedup4_5)

combinedstars4 <- c(starsplit4_1,starsplit4_2, starsplit4_3, starsplit4_4, starsplit4_5)

combineddate4 <- c(subsetdate4_1, subsetdate4_2, subsetdate4_3, subsetdate4_4, subsetdate4_5)

combinedtext4 <- c(cleantext4_1, cleantext4_2, cleantext4_3, cleantext4_4, cleantext4_5)

product4df <- data.frame( ProductName = productname4,
                          reviewers = combinedreviewers4,
                          star_rates = combinedstars4,
                         date_of_review = combineddate4,
                         text_review = combinedtext4)
product4df
write.csv(product4df, "FourthProduct.csv")
```
```{r}
urlprod5_1 <- "https://www.amazon.com/GTPLAYER-Computer-Footrest-Adjustable-360%C2%B0-Swivel/product-reviews/B0BBPRZHRX/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
session5_1 <- bow(urlprod5_1, user_agent = "educational purposes")
url5_1 <- read_html(urlprod5_1)
```

```{r}
#get the reviewer's name
reviewername5_1 <- url5_1 %>% 
  html_nodes("span.a-profile-name") %>%
  html_text()

subsetreviewername5_1 <- reviewername5_1[3:14] #subset the 5th page reviewer to get only the 10 reviewers.
removedup5_1 <- subsetreviewername5_1[-c(3, 8)] #remove the duplicate
#get the star ratings of the reviewer
starreview5_1 <- url5_1 %>% 
  html_nodes("a.review-title") %>%
  html_text()

#split it to exclude the title review
starsplit5_1 <- str_extract(starreview5_1, "^\\d+\\.\\d+ out of \\d+ stars")
starsplit5_1

#get the review title and use gsub to remove the star ratings
review_titles5_1 <- lapply(starreview5_1, function(revtitle5_1) {
  revtitle5_1 <- gsub("\\d+\\.\\d+ out of \\d+ stars", " ", revtitle5_1)
  revtitle5_1 <- trimws(revtitle5_1)
  return(revtitle5_1)
})
review_titles5_1


#get the date of the review
dateofreview5_1 <- url5_1 %>%
  html_nodes("span.review-date") %>%
  html_text()
#split the date from the text
splitdatereview5_1 <- str_extract(dateofreview5_1, "\\b\\w+ \\d{1,2}, \\d{4}\\b")

subsetdate5_1 <- splitdatereview5_1[3:12] #subset dates to remove first 2 content to get only the reviews not the top 2.
subsetdate5_1
#get the content of the review
textreview4_5 <- url4_5 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

#remove emojis from the text
remove_emojis4_5 <- function(textreview4_5) {
  str_remove_all(textreview4_5, "[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251\U0001F004]+")
}
textreview4_5 <- remove_emojis4_5(textreview4_5)

#get the clean text without white spaces
cleantext4_5 <- trimws(textreview4_5)
cleantext4_5
```









































